### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by marcusaaronb** [meliodaaf/virus_total_url_checker#1]
ModuleNotFoundError: No module named 'requests'

**Comment by clarencesubia** [comment]
You need to install the modules first like so...

pip3 install requests
pip3 install argparse

If you do not have the pip installed, you can install it using command sudo apt install python3-pip

**Comment by marcusaaronb** [comment]
ModuleNotFoundError: No module named 'pwinput'

**Comment by marcusaaronb** [comment]
Working na thanks
